import 'package:pdv_project_teste_1/Models/Produto.dart';
import 'package:pdv_project_teste_1/Models/venda.dart';

List<Venda> listaVendas = [
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // ),
  // Venda(
  //   nomeVenda: 'v01',
  //   valor: 20.00,
  //   listaProdutos: [
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //     Produto(nome: 'Carne', valor: 5.00),
  //   ],
  //   nomeComprador: 'Jorge',
  //   dataVenda: DateTime.now(),
  // )
];
